"""
Finetune on non-OpenAI models via opbdh
(https://github.com/lumpenspace/opbdh -- "Open the Pod Bay Door, Hal").

raft prepares a self-contained run directory (LoRA SFT script +
requirements.txt + the chat-format dataset); opbdh bundles that
directory to a GPU pod, runs it against the chosen huggingface model,
and syncs results/ (the trained adapter) back home.
"""

import json
import os
from typing import Any, Dict, List, Optional

from .interactive import ask, bail, confirm

OPBDH_INSTALL_HINT = (
    "opbdh is not installed. Install it with:\n"
    "  pip install opbdh\n"
    "then run `opbdh config wizard` to set up your provider credentials."
)

# Model-name prefixes OpenAI accepts for finetuning; anything else is
# routed to huggingface via opbdh. Extend via RAFT_OAI_FINETUNABLE
# (comma-separated prefixes).
OPENAI_FINETUNABLE_PREFIXES = (
    "gpt-3.5-turbo",
    "gpt-4o-mini",
    "gpt-4o-2024",
    "gpt-4.1-mini",
    "gpt-4.1-nano",
    "gpt-4.1-2025",
    "davinci-002",
    "babbage-002",
)

RUN_REQUIREMENTS = """\
transformers>=4.44
trl>=0.12
peft>=0.13
datasets>=2.20
accelerate>=0.34
"""

RUN_SCRIPT = '''\
"""LoRA SFT run generated by raft; executed on a GPU pod by opbdh."""

import json
import os
from pathlib import Path

from datasets import Dataset
from peft import LoraConfig
from trl import SFTConfig, SFTTrainer

MODEL_ID = os.environ["OPBDH_MODEL_ID"]
RESULTS = Path(os.environ.get("OPBDH_RESULTS_DIR", "results"))
RESULTS.mkdir(parents=True, exist_ok=True)

here = Path(__file__).parent
rows = [json.loads(line) for line in (here / "train.jsonl").open()]
dataset = Dataset.from_list(rows)
print(f"training {MODEL_ID} on {len(dataset)} conversations")

trainer = SFTTrainer(
    model=MODEL_ID,
    train_dataset=dataset,
    args=SFTConfig(
        output_dir=str(RESULTS / "checkpoints"),
        num_train_epochs=int(os.environ.get("RAFT_EPOCHS", "3")),
        per_device_train_batch_size=1,
        gradient_accumulation_steps=8,
        learning_rate=2e-4,
        bf16=True,
        logging_steps=10,
        save_strategy="epoch",
    ),
    peft_config=LoraConfig(
        r=16,
        lora_alpha=32,
        target_modules="all-linear",
        task_type="CAUSAL_LM",
    ),
)
trainer.train()
trainer.save_model(str(RESULTS / "adapter"))
print(f"adapter saved to {RESULTS / 'adapter'}")
'''


def is_openai_finetunable(model: str) -> bool:
    """Check whether a model id can be finetuned on the OpenAI API."""
    extra = tuple(
        p.strip()
        for p in os.environ.get("RAFT_OAI_FINETUNABLE", "").split(",")
        if p.strip()
    )
    return model.startswith(OPENAI_FINETUNABLE_PREFIXES + extra)


def load_opbdh():
    """Import opbdh, or exit with an install hint."""
    try:
        import opbdh
    except ImportError:
        bail(OPBDH_INSTALL_HINT)
    if not hasattr(opbdh, "launch"):
        bail(
            "the installed opbdh is too old for raft 2.0 (no Python API).\n"
            "Upgrade with: pip install -U opbdh"
        )
    return opbdh


def parse_opbdh_flags(flags: List[str]) -> Dict[str, Any]:
    """
    Turn passthrough CLI flags into opbdh keyword overrides.

    `--vram-gb 48 --max-spend 5` becomes `{"vram_gb": 48, "max_spend": 5.0}`;
    a flag with no value is treated as a boolean switch.
    """
    overrides: Dict[str, Any] = {}
    index = 0
    while index < len(flags):
        flag = flags[index]
        if not flag.startswith("--"):
            bail(f"unexpected argument for opbdh: {flag}")
        key = flag[2:].replace("-", "_")
        if "=" in key:
            key, raw = key.split("=", 1)
            index += 1
        elif index + 1 < len(flags) and not flags[index + 1].startswith("--"):
            raw = flags[index + 1]
            index += 2
        else:
            overrides[key] = True
            index += 1
            continue
        overrides[key] = coerce_flag_value(raw)
    return overrides


def coerce_flag_value(raw: str) -> Any:
    """Coerce a CLI flag string to int/float/bool where it plainly is one."""
    if raw.lower() in ("true", "false"):
        return raw.lower() == "true"
    for cast in (int, float):
        try:
            return cast(raw)
        except ValueError:
            continue
    return raw


def prepare_run_dir(name: str) -> str:
    """
    Create data/{name}_hf_run/ with the training script, requirements
    and the dataset (messages stripped to role/content for chat
    templates).

    Returns:
        str: The run directory path.
    """
    source = f"data/{name}_finetune_openai.jsonl"
    if not os.path.exists(source):
        bail(f"{source} not found -- run `raft ft:gen {name}` first")

    run_dir = f"data/{name}_hf_run"
    os.makedirs(run_dir, exist_ok=True)

    with open(source) as src, open(f"{run_dir}/train.jsonl", "w") as out:
        for line in src:
            if not line.strip():
                continue
            item = json.loads(line)
            messages = [
                {"role": m["role"], "content": m["content"]}
                for m in item["messages"]
                if m.get("content")
            ]
            out.write(json.dumps({"messages": messages}) + "\n")

    with open(f"{run_dir}/run.py", "w") as f:
        f.write(RUN_SCRIPT)
    with open(f"{run_dir}/requirements.txt", "w") as f:
        f.write(RUN_REQUIREMENTS)
    return run_dir


def pick_model_interactively(opbdh: Any) -> str:
    """Pick a huggingface model, optionally searching the hub via opbdh."""
    while True:
        if confirm("Search huggingface for a model?", default=True):
            query = ask("Search query", "instruct")
            try:
                for model_id in opbdh.search_models(query, limit=15):
                    print(f"  {model_id}")
            except Exception as e:
                print(f"  (search unavailable: {e})")
        model = ask("Huggingface model id (e.g. Qwen/Qwen2.5-7B-Instruct)")
        if "/" in model:
            return model
        print("That doesn't look like a huggingface id (expected org/name).")


def run_hf_finetune(
    name: str,
    model: str,
    opbdh_args: Optional[List[str]] = None,
    interactive: bool = False,
) -> None:
    """
    Launch a huggingface finetune on a GPU pod via opbdh.

    Args:
        name (str): Dataset name.
        model (str): Huggingface model id (asked interactively if empty).
        opbdh_args (Optional[List[str]]): Extra flags forwarded verbatim
            to `opbdh launch` (on top of any opbdh.json config).
        interactive (bool): Ask for missing settings instead of relying
            on opbdh defaults/config.
    """
    opbdh = load_opbdh()
    if not model:
        if not interactive:
            bail("no model given -- pass --model <org/name> or drop --no-interactive")
        model = pick_model_interactively(opbdh)

    run_dir = prepare_run_dir(name)
    overrides = parse_opbdh_flags(list(opbdh_args or []))

    if interactive and "vram_gb" not in overrides:
        estimate = opbdh.estimate_model_size(model)
        if estimate.size_gb:
            print(
                f"\n{model} weighs about {estimate.size_gb:.1f} GB; "
                f"a network volume of ~{opbdh.suggest_volume_gb(estimate)} GB would cache it."
            )
        vram = ask("Minimum GPU VRAM in GB (empty = opbdh default)", "")
        if vram:
            overrides["vram_gb"] = int(vram)
        spend = ask("Max total spend in $ (empty = opbdh default)", "")
        if spend:
            overrides["max_spend"] = float(spend)

    plan = opbdh.plan(run_dir, model=model, **overrides)
    summary = opbdh.summarize(plan)
    print(
        f"\nLaunching on {summary['gpu_candidates'][0]} "
        f"(~${summary['estimated_hourly_dollars']}/hr, "
        f"max spend ${summary['max_spend_dollars']}).\n"
    )

    try:
        result = opbdh.launch(
            run_dir,
            model=model,
            progress=True,
            on_event=lambda event: print(f"  [{event.kind}] {event.message}"),
            **overrides,
        )
    except opbdh.MaxSpendReached as e:
        bail(f"stopped by the spend guard: {e}")
    except RuntimeError as e:
        bail(f"the finetune failed on the pod: {e}")

    print(f"\nDone. The LoRA adapter is in {result.outputs_dir / 'adapter'}.")
